### ISSUE TITLE
It doesn't work in 3s_vs_5z

### ISSUE THREAD

**Issue by Zarzard** [morning9393/Optimal-Baseline-for-Multi-agent-Policy-Gradients#1]
Hi! I have just read your paper and want to run the code in this repo. I follow the default hyperparameter setting in the code, but the win rate always stays at 0 in 3s\_vs\_5z, while it works in 3s\_vs\_3z.

**Comment by Zarzard** [comment]
I meant the mappo code.

**Comment by morning9393** [comment]
Hiya~ sorry for my late response...

I think the reason might be the default actor lr in this repo is 5e-4, while the lr used for 3s_vs_5z in the paper is 1e-3 (in Appendix F)

My suggestion is that you could have a look for the "eval_average_episode_rewards" in your tensorboard. If it is going up, that should be ok, then you could set the actor lr to 1e-3 (in config/config_smac.py) and it should be able to replicate our plots. 

Thx so much for your attention!
